cc_binary(
    name = "find_pair",
    srcs = ["find_pair.cc"],
)

cc_binary(
    name = "merge_sort",
    srcs = ["merge_sort.cc"],
)

cc_binary(
    name = "heap_sort",
    srcs = ["heap_sort.cc"],
    deps = ["//x4444/ds:heap_lib"]
)
