cc_binary(
    name = "remove_elem",
    srcs = ["remove_elem.cc"],
)

cc_binary(
    name = "remove_dup",
    srcs = ["remove_dup.cc"],
)

cc_binary(
    name = "remove_dup2",
    srcs = ["remove_dup2.cc"],
)

cc_binary(
    name = "major_elem",
    srcs = ["major_elem.cc"],
)

cc_binary(
    name = "rotate_arr",
    srcs = ["rotate_arr.cc"],
)

cc_binary(
    name = "max_profit",
    srcs = ["max_profit.cc"],
)

cc_binary(
    name = "max_profit2",
    srcs = ["max_profit2.cc"],
)

cc_binary(
    name = "climb_stairs",
    srcs = ["climb_stairs.cc"],
)

cc_binary(
    name = "longest_common_prefix",
    srcs = ["longest_common_prefix.cc"],
)

cc_binary(
    name = "len_of_last_word",
    srcs = ["len_of_last_word.cc"],
)

cc_binary(
    name = "graph_valid_binary_tree",
    srcs = ["graph_valid_binary_tree.cc"],
)

cc_binary(
    name = "permutations",
    srcs = ["permutations.cc"],
)

cc_binary(
    name = "permutations2",
    srcs = ["permutations2.cc"],
)

cc_binary(
    name = "jump_game",
    srcs = ["jump_game.cc"],
)

cc_binary(
    name = "jump_game2",
    srcs = ["jump_game2.cc"],
)

cc_binary(
    name = "max_sub_array",
    srcs = ["max_sub_array.cc"],
)

cc_binary(
    name = "h_index",
    srcs = ["h_index.cc"],
)

cc_binary(
    name = "first_occurrence",
    srcs = ["first_occurrence.cc"],
)

cc_binary(
    name = "foo",
    srcs = ["foo.cc"],
)

cc_binary(
    name = "random_set",
    srcs = ["random_set.cc"],
)

cc_binary(
    name = "prod_except_self",
    srcs = ["prod_except_self.cc"],
)

cc_binary(
    name = "gas_station",
    srcs = ["gas_station.cc"],
)

cc_binary(
    name = "candy",
    srcs = ["candy.cc"],
)

cc_binary(
    name = "roman_to_int",
    srcs = ["roman_to_int.cc"],
)

cc_binary(
    name = "int_to_roman",
    srcs = ["int_to_roman.cc"],
)

cc_binary(
    name = "reverse_words",
    srcs = ["reverse_words.cc"],
)

cc_binary(
    name = "trap",
    srcs = ["trap.cc"],
)

cc_binary(
    name = "zigzag",
    srcs = ["zigzag.cc"],
)

cc_binary(
    name = "text_justification",
    srcs = ["text_justification.cc"],
)

cc_binary(
    name = "valid_palindrome",
    srcs = ["valid_palindrome.cc"],
)

cc_binary(
    name = "is_subseq",
    srcs = ["is_subseq.cc"],
)

cc_binary(
    name = "two_sum_sorted",
    srcs = ["two_sum_sorted.cc"],
)

cc_binary(
    name = "two_sum",
    srcs = ["two_sum.cc"],
)

cc_binary(
    name = "container_with_most_water",
    srcs = ["container_with_most_water.cc"],
)

cc_binary(
    name = "3sum",
    srcs = ["3sum.cc"],
)

cc_binary(
    name = "min_size_subarray",
    srcs = ["min_size_subarray.cc"],
)

cc_binary(
    name = "longest_substr_wo_repeating",
    srcs = ["longest_substr_wo_repeating.cc"],
)

cc_binary(
    name = "substring_w_concatenation_all_words",
    srcs = ["substring_w_concatenation_all_words.cc"],
)

cc_binary(
    name = "min_window_substr",
    srcs = ["min_window_substr.cc"],
)

cc_binary(
    name = "valid_sudoku",
    srcs = ["valid_sudoku.cc"],
)

cc_binary(
    name = "spiral_matrix",
    srcs = ["spiral_matrix.cc"],
)

cc_binary(
    name = "rotate_matrix",
    srcs = ["rotate_matrix.cc"],
)

cc_binary(
    name = "set_matrix_zeros",
    srcs = ["set_matrix_zeros.cc"],
)

cc_binary(
    name = "game_of_life",
    srcs = ["game_of_life.cc"],
)

cc_binary(
    name = "ransom_note",
    srcs = ["ransom_note.cc"],
)

cc_binary(
    name = "isomorphic_strings",
    srcs = ["isomorphic_strings.cc"],
)

cc_binary(
    name = "group_anagrams",
    srcs = ["group_anagrams.cc"],
)

cc_binary(
    name = "restore_alphabet",
    srcs = ["restore_alphabet.cc"],
)

cc_binary(
    name = "valid_anagram",
    srcs = ["valid_anagram.cc"],
)

cc_binary(
    name = "word_pattern",
    srcs = ["word_pattern.cc"],
)

cc_binary(
    name = "happy_number",
    srcs = ["happy_number.cc"],
)

cc_binary(
    name = "contains_duplicate_2",
    srcs = ["contains_duplicate_2.cc"],
)

cc_binary(
    name = "longest_conseq_seq",
    srcs = ["longest_conseq_seq.cc"],
)

cc_binary(
    name = "summary_ranges",
    srcs = ["summary_ranges.cc"],
)

cc_binary(
    name = "merge_intervals",
    srcs = ["merge_intervals.cc"],
)

cc_binary(
    name = "insert_interval",
    srcs = ["insert_interval.cc"],
)

cc_binary(
    name = "min_arrows_burst_baloons",
    srcs = ["min_arrows_burst_baloons.cc"],
)

cc_binary(
    name = "valid_parentheses",
    srcs = ["valid_parentheses.cc"],
)
