cc_binary(
    name = "remove_elem",
    srcs = ["remove_elem.cc"],
)

cc_binary(
    name = "remove_dup",
    srcs = ["remove_dup.cc"],
)

cc_binary(
    name = "remove_dup2",
    srcs = ["remove_dup2.cc"],
)

cc_binary(
    name = "major_elem",
    srcs = ["major_elem.cc"],
)