cc_library(
    name = "heap_lib",
    hdrs = ["heap.h"],
)

cc_binary(
    name = "heap",
    srcs = ["heap.cc"],
    deps = ["heap_lib"],
)

cc_binary(
    name = "hello",
    srcs = ["hello.cc"],
)
